export const CAREERS = [
  { name: 'Praktikant', xp: 0, pay: 1, slots: 1, perk: 'Dein erster eigener Schreibtisch' },
  { name: 'Werkstudent', xp: 80, pay: 1.18, slots: 2, perk: 'Ergonomische Maus & neue Tastatur' },
  {
    name: 'Junior Consultant',
    xp: 220,
    pay: 1.4,
    slots: 2,
    perk: 'Zweiter Monitor & Analyseaufträge',
  },
  { name: 'Consultant', xp: 470, pay: 1.7, slots: 3, perk: 'Premiumstuhl & Kundenmeetings' },
  {
    name: 'Senior Consultant',
    xp: 850,
    pay: 2.05,
    slots: 3,
    perk: 'Großer Schreibtisch & Senior Lounge',
  },
  { name: 'Project Manager', xp: 1450, pay: 2.5, slots: 4, perk: 'Eigener Projektbereich' },
  { name: 'Partner', xp: 2250, pay: 3.2, slots: 5, perk: 'Partnerbüro & Auszeichnung' },
];
export const RESTAURANTS = [
  {
    id: 'dogtown',
    name: 'DOGTOWN BURRITO CO.',
    address: 'Augustenstraße 16',
    kind: 'Burritos · Spielsortiment',
    color: '#be6541',
    x: 17,
    z: 88,
    source: 'https://neotaste.com/de/restaurants/munich/dogtown-burrito-co',
    foods: [
      { name: 'California Burrito', price: 9.5, hunger: 50, happy: 12, energy: 5, focus: 0 },
      { name: 'Veggie Burrito', price: 9.5, hunger: 50, happy: 12, energy: 8, focus: 4 },
      { name: 'Limonade', price: 3.5, hunger: 0, happy: 7, energy: 8, focus: 0 },
    ],
  },
  {
    id: 'seen',
    name: 'SEEN',
    address: 'Augustenstraße 7',
    kind: 'Sichuan · Fine Dining',
    color: '#6e2936',
    x: -17,
    z: 72,
    source: 'https://seen-restaurant.de/',
    foods: [
      { name: 'Sichuan Aubergine', price: 16.9, hunger: 62, happy: 20, energy: 8, focus: 5 },
      { name: 'Jasmintee', price: 3.8, hunger: 0, happy: 6, energy: 12, focus: 15 },
      { name: 'Sichuan Menü', price: 29, hunger: 90, happy: 35, energy: 10, focus: 0 },
    ],
  },
  {
    id: 'bao',
    name: 'MAMMA BAO',
    address: 'Augustenstraße 31',
    kind: 'Biang-Biang-Nudeln · Bao',
    color: '#df593c',
    x: -17,
    z: 10,
    source: 'https://mammabao.de/',
    foods: [
      { name: 'Biang-Biang-Nudeln', price: 13.9, hunger: 65, happy: 22, energy: 8, focus: -5 },
      { name: 'Gedämpfte Bao', price: 8.5, hunger: 45, happy: 12, energy: 5, focus: 0 },
      { name: 'Grüner Tee', price: 3.2, hunger: 0, happy: 5, energy: 16, focus: 16 },
    ],
  },
  {
    id: 'palm',
    name: 'PALMTREECLUB',
    address: 'Augustenstraße 43',
    kind: 'Glutenfrei · Bowls · Kaffee',
    color: '#53866c',
    x: -17,
    z: -23,
    source: 'https://www.palmtreeclub.de/',
    foods: [
      { name: 'Lunch Bowl', price: 14.5, hunger: 60, happy: 18, energy: 15, focus: 15 },
      { name: 'Espresso', price: 3.2, hunger: 0, happy: 5, energy: 25, focus: 20 },
      { name: 'Bananenbrot', price: 4.9, hunger: 28, happy: 12, energy: 10, focus: 3 },
    ],
  },
  {
    id: 'gyoza',
    name: 'GYOZA BAR',
    address: 'Augustenstraße 47a',
    kind: 'Japanisch · Dumplings',
    color: '#243f63',
    x: -17,
    z: -64,
    source: 'https://gyozabar.info/de/home/',
    foods: [
      { name: 'Gyoza, 8 Stück', price: 10.9, hunger: 50, happy: 18, energy: 5, focus: 8 },
      { name: 'Ramen Bowl', price: 15.5, hunger: 75, happy: 22, energy: 12, focus: 5 },
      { name: 'Matcha', price: 4.2, hunger: 0, happy: 6, energy: 20, focus: 18 },
    ],
  },
  {
    id: 'wirt',
    name: 'WIRTSHAUS MAXVORSTADT',
    address: 'Augustenstraße 53',
    kind: 'Bayerisch · Wirtshaus',
    color: '#8f704b',
    x: -17,
    z: -98,
    source: 'https://www.wirtshaus-maxvorstadt.de/',
    foods: [
      { name: 'Käsespätzle', price: 14.9, hunger: 75, happy: 25, energy: 5, focus: -8 },
      { name: 'Brezn & Obazda', price: 8.5, hunger: 45, happy: 15, energy: 5, focus: 0 },
      { name: 'Apfelschorle', price: 4.5, hunger: 0, happy: 8, energy: 10, focus: 10 },
    ],
  },
  {
    id: 'mentors',
    name: 'MENTOR’S',
    address: 'Augustenstraße 62',
    kind: 'Holzofenpizza · Restaurant Bar',
    color: '#bd864d',
    x: 17,
    z: -73,
    source: 'https://mentors-holzofenpizza.de/impressum/',
    foods: [
      { name: 'Pizza Margherita', price: 13.9, hunger: 65, happy: 20, energy: 6, focus: -5 },
      { name: 'Pizza Verdure', price: 15.9, hunger: 70, happy: 24, energy: 10, focus: 0 },
      { name: 'Espresso doppio', price: 4.2, hunger: 0, happy: 5, energy: 30, focus: 22 },
    ],
  },
];
export const TASKS = [
  {
    type: 'slide',
    title: 'Der Gartencenter-Markt auf einer Folie',
    brief:
      'Bitte bis 12:30 eine Marktübersicht erstellen. Drei Segmente, klare Storyline. Das Logo bitte 3 Pixel nach links.',
    base: 24.5,
    min: 1,
    rep: 0,
    minutes: 253,
    location: 'Dein BBE-Arbeitsplatz',
  },
  {
    type: 'market',
    title: 'Marktpotenziale verdichten',
    brief:
      'Wähle belastbare Fakten für die Management Summary. Bauchgefühl zählt heute ausnahmsweise nicht als Quelle.',
    base: 32,
    min: 1,
    rep: 0,
    minutes: 300,
    location: 'Dein BBE-Arbeitsplatz',
  },
  {
    type: 'benchmark',
    title: 'Lunch-Benchmark Augustenstraße',
    brief:
      'Fotografiere die Speisekarten von drei verschiedenen Restaurants. Danach bitte die Erkenntnisse am BBE-PC abgeben.',
    base: 38,
    min: 1,
    rep: 0,
    minutes: 400,
    location: 'Drei Restaurants → BBE',
  },
  {
    type: 'excel',
    title: 'Marge schlägt Bauchgefühl',
    brief: 'Berechne die Handelsmargen, identifiziere den Spitzenreiter und sortiere die Umsätze.',
    base: 34,
    min: 2,
    rep: 10,
    minutes: 280,
    location: 'Dein BBE-Arbeitsplatz',
  },
  {
    type: 'mystery',
    title: 'Mystery Shopping: Service-Check',
    brief:
      'Besuche MAMMA BAO, prüfe die Karte und sprich mit dem Service. Dokumentiere Küche und Einstiegsgericht am BBE-PC.',
    base: 44,
    min: 2,
    rep: 12,
    minutes: 350,
    location: 'MAMMA BAO → BBE',
  },
  {
    type: 'competition',
    title: 'Wettbewerber richtig einordnen',
    brief:
      'Ordne die sechs Marktteilnehmer dem passenden Geschäftsmodell zu. Beratung beginnt mit einer brauchbaren Schublade.',
    base: 43,
    min: 3,
    rep: 30,
    minutes: 330,
    location: 'Dein BBE-Arbeitsplatz',
  },
  {
    type: 'lunch',
    title: 'Lunch für das Projektteam',
    brief:
      'Bestelle bei PALMTREECLUB eine Meeting-Lieferung. Die BBE übernimmt die Kosten. Bringe sie zum Empfang.',
    base: 42,
    min: 2,
    rep: 10,
    minutes: 280,
    location: 'PALMTREECLUB → BBE-Empfang',
  },
  {
    type: 'meeting',
    title: 'Kundentermin: Erwartungsmanagement',
    brief:
      'Besuche den Kunden an der Gabelsbergerstraße. Höre zu, kläre das Ziel und formuliere eine belastbare Zusage.',
    base: 55,
    min: 4,
    rep: 65,
    minutes: 400,
    location: 'Kundenbüro → BBE',
  },
  {
    type: 'interview',
    title: 'Die Stimme der Kundschaft',
    brief:
      'Cluster sechs Interviewaussagen nach Preis, Sortiment und Service. „Alles irgendwie wichtig“ ist kein Cluster.',
    base: 48,
    min: 3,
    rep: 35,
    minutes: 350,
    location: 'Dein BBE-Arbeitsplatz',
  },
  {
    type: 'revision',
    title: 'final_final_v4_wirklich_final.pptx',
    brief:
      'Sieben kleine Anpassungen. Wirklich die letzten. Korrigiere Überschrift, Farbe, Chart und Alignment.',
    base: 58,
    min: 3,
    rep: 35,
    minutes: 350,
    location: 'Dein BBE-Arbeitsplatz',
  },
];
export const ACHIEVEMENTS = [
  ['fire-story', 'Himmlischer Hotfix', 'Den brennenden Laptop rechtzeitig zu Benjamin gebracht.'],
  [
    'workshop-story',
    'Persönlich geliefert.',
    'Mit Tobias den Workshop-Koffer zum Marienplatz gebracht und den Abendworkshop abgeschlossen.',
  ],
  ['brawler', 'Feedback mit Nachdruck', 'Eine Figur im Arcade-Modus zu Boden bringen.'],
  ['driver', 'Dienstwagenprivileg', '100 Meter selbst fahren.'],
  ['wc', 'Sanitär-Consultant', 'Drei WC-Minispiele abschließen.'],
  ['aim', 'Zielsicher', 'Mindestens 90 % Treffgenauigkeit auf dem WC.'],
  ['first', 'Erste Rechnung', 'Deinen ersten BBE-Auftrag abschließen.'],
  ['slide', 'Slide Master', '5 Folien mit mindestens 95 % abliefern.'],
  ['pixel', 'Pixel Perfect', '100 % Alignment erreichen.'],
  ['veteran', 'BBE-Urgestein', '50 Aufträge abschließen.'],
  ['gourmet', 'Augustenstraßen-Gourmet', 'In allen Restaurants essen.'],
  ['bottle', 'Pfandlord', '100 Flaschen abgeben.'],
  ['coffee', 'Koffeinberater', '10 Kaffee an einem Tag trinken.'],
  ['revision', 'final_final_v7.pptx', '7 Revisionen abschließen.'],
  ['partner', 'Partner Material', 'Karrierestufe 7 erreichen.'],
];
export const QUIPS = [
  'Kannst du das noch etwas managementtauglicher machen?',
  'Bitte nur noch eine kleine Änderung.',
  'Die Folie braucht mehr Storyline.',
  'Kannst du daraus noch schnell einen One-Pager machen?',
  'Der Kunde hat die Zahlen geändert. Natürlich nach Freigabe.',
  'Der Drucker hat deine Folie als abstrakte Kunst interpretiert.',
  'Synergien sind auch nur Freundschaften mit Budget.',
];
export const euro = (v) =>
  new Intl.NumberFormat('de-DE', { style: 'currency', currency: 'EUR' }).format(v);
export const clamp = (v, a = 0, b = 100) => Math.min(b, Math.max(a, v));
