// Quizssoir 3: welcoming trivia first, wordplay in the middle, reasoning late.
// Real BBE facts checked on the linked official pages on 2026-10-02.
// Fictional people and events are explicitly qualified as part of the game.
export const QUIZ_TRIVIA_SOURCES = Object.freeze({
  company: 'https://www.bbe.de/de/uber-uns/',
  address: 'https://www.bbe.de/de/impressum/',
  services: 'https://www.bbe.de/de/leistungen/',
  locations: 'https://www.bbe.de/de/kontakt/standorte/',
  group: 'https://www.bbe.de/de/uber-uns/firmenverbund/',
  erfa: 'https://www.bbe.de/de/leistungen/managementberatung/erfa-erfahrungsaustausch/',
  scouts: 'https://www.bbe.de/de/aktuelles/blog/was-zum-sehen-neue-clip-serie-bbe-retail-scouts/',
  publications: 'https://www.bbe.de/de/aktuelles/',
  newsletter: 'https://www.bbe.de/de/aktuelles/newsletter/',
  marienplatz: 'https://www.muenchen.de/en/sights/attractions/marienplatz-munichs-old-town',
  munich: 'https://www.muenchen.de/en/sights/sightseeing-25-top-sights-and-attractions-munich',
  index: 'https://www.duden.de/rechtschreibung/Index',
  isar: 'https://stadt.muenchen.de/infos/isar.html',
});
const S = QUIZ_TRIVIA_SOURCES;

// A string reuses the entire original record, including its original level,
// text, answers and metadata. Only new entries receive a new v3 ID.
const TRIVIA_TIERS = [
  [
    'q01a',
    'q01b',
    'q01c',
    [
      'Spielwelt',
      'Wo beginnt der normale Arbeitstag in diesem Spiel?',
      'Im BBE-Büro',
      ['Auf einem Kreuzfahrtschiff', 'In einer Raumstation', 'In einem Iglu'],
      'Im BBE-Büro. Der Kaffee ist näher als die erste Beförderung.',
    ],
    [
      'Trivia',
      'In welcher Pfanne lässt sich ein Thai-Curry besonders gut schwenken?',
      'Im Wok',
      ['Im Sieb', 'Im Brotkorb', 'Im Eiswürfelbehälter'],
      'Im Wok. Ein Workstream hat dagegen selten einen Griff.',
    ],
    [
      'Trivia',
      'Womit tippt man normalerweise einen Text am Computer?',
      'Mit der Tastatur',
      ['Mit dem Locher', 'Mit dem Wasserglas', 'Mit der Schreibtischlampe'],
      'Mit der Tastatur. Der Locher liefert nur sehr kurze Texte.',
    ],
    [
      'Spielwelt',
      'Was kann man in der Spielwelt sammeln und am Automaten abgeben?',
      'Pfandflaschen',
      ['Regenwolken', 'Ampelphasen', 'Meeting-Einladungen'],
      'Pfandflaschen. Eine kleine Rendite ganz ohne Strategiefolie.',
    ],
    [
      'Spielwelt',
      'Welches Essen steckt schon im Namen von Dogtown Burrito?',
      'Burrito',
      ['Sushi', 'Spätzle', 'Risotto'],
      'Burrito. Hier darf die Markenpositionierung ausnahmsweise satt machen.',
    ],
    [
      'Trivia',
      'Welcher Gegenstand versorgt eine echte Büropflanze mit Licht?',
      'Eine Lampe',
      ['Ein Aktenordner', 'Ein Briefumschlag', 'Ein Radiergummi'],
      'Eine Lampe kann Licht liefern. Lob allein reicht dem Ficus nicht.',
    ],
    [
      'Spielwelt',
      'In welchem Raum des Spiels steht das Portal Quizssoir?',
      'In der Toilette',
      ['Im Helikopter', 'Im Kühlraum', 'Im Tresor'],
      'In der Toilette. Selten führte ein kurzer Gang so weit nach oben.',
    ],
  ],
  [
    'q02a',
    'q02b',
    'q02c',
    [
      'Trivia',
      'Was kombiniert ein Headset?',
      'Kopfhörer und Mikrofon',
      ['Drucker und Scanner', 'Tasse und Untertasse', 'Locher und Tacker'],
      'Kopfhörer und Mikrofon. Damit hört man auch die letzte kleine Änderung.',
    ],
    [
      'BBE',
      'Welche Rechtsform trägt die BBE Handelsberatung im Firmennamen?',
      'GmbH',
      ['AG', 'e. V.', 'OHG'],
      'GmbH. Das steht tatsächlich im Namen, nicht nur im Folienfuß.',
      S.address,
    ],
    [
      'Trivia',
      'Was legt man zum normalen Ausdrucken in das Papierfach?',
      'Papier',
      ['Kaffeefilter', 'Serviettenringe', 'Visitenkartenhalter'],
      'Papier. Der Drucker möchte trotz seiner Geräusche nicht gefüttert werden.',
    ],
    [
      'Trivia',
      'Womit schreibt man üblicherweise auf ein Whiteboard?',
      'Mit einem Whiteboardmarker',
      ['Mit einer Gabel', 'Mit einem Klebestift', 'Mit einem Flaschenöffner'],
      'Mit einem Whiteboardmarker. Die Strategie bleibt erfreulich abwischbar.',
    ],
    [
      'Spielwelt',
      'Welcher Platz liegt im Spiel nahe der BBE-Zentrale?',
      'Königsplatz',
      ['Alexanderplatz', 'Times Square', 'Potsdamer Platz'],
      'Der Königsplatz. Für diese Außenmission braucht es keinen Flugkostenantrag.',
    ],
    [
      'Trivia',
      'Welche Ampelfarbe bedeutet für Autofahrer normalerweise Halt?',
      'Rot',
      ['Grün', 'Violett', 'Türkis'],
      'Rot. Auch ein dringender Workshop macht daraus keine Empfehlung.',
    ],
    [
      'Trivia',
      'Welche Zutat kann ein Thai-Curry cremig machen?',
      'Kokosmilch',
      ['Mineralwasser', 'Paniermehl', 'Puderzucker'],
      'Kokosmilch. Der Wok bekommt seine eigene Wohlfühlphase.',
    ],
  ],
  [
    'q03a',
    'q03b',
    'q03c',
    [
      'Trivia',
      'Welches Getränk wird aus Espresso und aufgeschäumter Milch zubereitet?',
      'Cappuccino',
      ['Darjeeling', 'Limonade', 'Apfelschorle'],
      'Cappuccino. Ein Milchschaumdiagramm ohne Datenproblem.',
    ],
    [
      'Trivia',
      'Welcher Fluss fließt durch München?',
      'Isar',
      ['Elbe', 'Oder', 'Seine'],
      'Die Isar. Ein Wasserlauf, der keinen Projektstatus braucht.',
      S.isar,
    ],
    [
      'Spielwelt',
      'Was erhältst du im Spiel für abgegebenes Pfand?',
      'Geld',
      ['Einen Doktortitel', 'Ein neues Wetter', 'Eine andere Hausnummer'],
      'Geld. Selbst die Flaschen leisten einen kleinen Beitrag zur Karriere.',
    ],
    [
      'Spielwelt',
      'Wo sitzt der Kandidat nach dem Quizssoir-Portal in der Show?',
      'Auf einem Quizstuhl',
      ['Im Waschbecken', 'Auf dem Drucker', 'Auf einem Autodach'],
      'Auf einem Quizstuhl. Das Portal ist kein Sitzplatzkonzept.',
    ],
    [
      'Trivia',
      'In welchem Bundesland liegt München?',
      'Bayern',
      ['Hessen', 'Sachsen', 'Saarland'],
      'Bayern. Der Standortcheck bleibt heute angenehm übersichtlich.',
      S.munich,
    ],
    [
      'Trivia',
      'Welches Computergerät trägt denselben Namen wie ein kleines Nagetier?',
      'Maus',
      ['Dachs', 'Otter', 'Igel'],
      'Die Maus. Bei dieser Büroausstattung ist Käse keine Betriebsausgabe.',
    ],
    [
      'BBE',
      'Welche Internetadresse gehört zur BBE Handelsberatung?',
      'bbe.de',
      ['bbe-mond.test', 'buerostuhl.invalid', 'folienfisch.example'],
      'bbe.de. Kurz genug, um auch auf die letzte Folie zu passen.',
      S.address,
    ],
  ],
  [
    'q04a',
    'q04b',
    [
      'Spielwelt',
      'In welchem Bereich arbeitet Benjamin in der Spielgeschichte?',
      'In der IT',
      ['In der Schneiderei', 'Im Planetarium', 'Im Weinberg'],
      'In der IT. Dort werden heiße Themen gelegentlich sehr wörtlich behandelt.',
    ],
    [
      'Trivia',
      'Welches Gerät macht aus einer Papierseite eine digitale Bilddatei?',
      'Ein Scanner',
      ['Ein Ventilator', 'Ein Aktenvernichter', 'Ein Wasserkocher'],
      'Ein Scanner. Der Aktenvernichter digitalisiert ausgesprochen endgültig.',
    ],
    [
      'Spielwelt',
      'Welches Getränk gehört zur Brauerei Brienner Bräu im Spiel?',
      'Bier',
      ['Bubble Tea', 'Tomatensaft', 'Kakao'],
      'Bier. Beim Maßkrugstemmen wird daraus zusätzlich ein Halteproblem.',
    ],
    [
      'Spielwelt',
      'Welche Straße ist im Spiel der wichtigste Restaurantbereich neben der BBE?',
      'Augustenstraße',
      ['Champs-Élysées', 'Baker Street', 'Wall Street'],
      'Die Augustenstraße. Die Lunch-Strategie hat damit eine Richtung.',
    ],
    [
      'BBE',
      'Wie ergänzt die BBE ihren Leitsatz: Wissen schafft ...?',
      'Zukunft',
      ['Parkplätze', 'Überstunden', 'Konfetti'],
      'Zukunft. Überstunden sind kein Bestandteil dieses Leitsatzes.',
      S.company,
    ],
    [
      'Trivia',
      'Was bedeutet das englische Wort Whiteboard wörtlich?',
      'Weiße Tafel',
      ['Blauer Ordner', 'Grüner Teppich', 'Roter Stift'],
      'Weiße Tafel. Nach dem Workshop ist das oft nur noch die Grundfarbe.',
    ],
    [
      'Trivia',
      'Welche Münchner Kirche ist für ihre beiden markanten Türme bekannt?',
      'Frauenkirche',
      ['Kölner Dom', 'Sagrada Família', 'Westminster Abbey'],
      'Die Frauenkirche. Zwei Türme, ganz ohne Vergleichsdiagramm.',
      S.munich,
    ],
    [
      'Trivia',
      'Was ist eine Visitenkarte?',
      'Eine kleine Karte mit Kontaktdaten',
      [
        'Ein Ausweis für Kaffeemaschinen',
        'Ein Parkticket fürs Büro',
        'Ein Blatt mit Rezeptzutaten',
      ],
      'Eine Karte mit Kontaktdaten. Der kürzeste One-Pager im Geschäftsleben.',
    ],
  ],
  [
    'q05a',
    'q05b',
    [
      'Trivia',
      'Wofür steht GmbH ausgeschrieben?',
      'Gesellschaft mit beschränkter Haftung',
      [
        'Gemeinschaft mit bester Haltung',
        'Gesellschaft mit besonderem Handel',
        'Geschäft mit bayerischem Hauptsitz',
      ],
      'Gesellschaft mit beschränkter Haftung. Die Zahl der Abkürzungen ist dagegen unbeschränkt.',
    ],
    [
      'Trivia',
      'Was ist ein Jour fixe im Bürokalender?',
      'Ein regelmäßig stattfindender Termin',
      ['Eine Druckerpatrone', 'Ein Rollkoffer', 'Ein französischer Käse'],
      'Ein regelmäßiger Termin. Die Tagesordnung ist meist beweglicher als der Termin.',
    ],
    [
      'Trivia',
      'Welches Gebäck erkennt man an seiner verschlungenen Form?',
      'Brezel',
      ['Baguette', 'Toastbrot', 'Ciabatta'],
      'Die Brezel. Schon vor dem ersten Workshop sauber verschlungen.',
    ],
    [
      'Trivia',
      'Welches Bürogerät verbindet Papierseiten mit einer Metallklammer?',
      'Tacker',
      ['Locher', 'Scanner', 'Beamer'],
      'Der Tacker. So bleibt wenigstens das Handout zusammen.',
    ],
    [
      'BBE',
      'Über welchen Kanal erhält man den BBE-Newsletter?',
      'Per E-Mail',
      ['Als Flaschenpost', 'Über Rauchzeichen', 'Auf Kassenzetteln'],
      'Per E-Mail. Der Posteingang erweitert sein Retail-Wissen.',
      S.newsletter,
    ],
    [
      'Trivia',
      'Was bedeutet das englische Wort Retail?',
      'Einzelhandel',
      ['Raumfahrt', 'Rückenschwimmen', 'Straßenbau'],
      'Einzelhandel. Die deutsche Übersetzung passt sogar ohne Abkürzung auf eine Folie.',
    ],
    [
      'Trivia',
      'Wen befragt ein Publikumjoker in einer Quizshow?',
      'Das Studiopublikum',
      ['Nur den Beleuchter', 'Die Wetterstation', 'Den Paketdienst'],
      'Das Studiopublikum. Endlich eine Abstimmung, die absichtlich alle einschließt.',
    ],
    [
      'Trivia',
      'An welchem Münchner Platz steht das Neue Rathaus?',
      'Am Marienplatz',
      ['Am Potsdamer Platz', 'Am Trafalgar Square', 'Am Alexanderplatz'],
      'Am Marienplatz. Der Termin beim Rathaus ist damit geografisch geklärt.',
      S.marienplatz,
    ],
  ],
  [
    [
      'BBE',
      'Wie heißt das Videoformat, mit dem BBE Einblicke in Läden und Handelskonzepte gibt?',
      'BBE Retail Scouts',
      ['BBE Retail Radar', 'BBE Store Stories', 'BBE Handelsinsider'],
      'BBE Retail Scouts schaut sich Handelskonzepte vor Ort an. Feldarbeit mit Kamera.',
      S.scouts,
    ],
    [
      'BBE',
      'Welche Stadt nennt BBE neben München als eigenen Standort?',
      'Hamburg',
      ['Hannover', 'Nürnberg', 'Bremen'],
      'Hamburg gehört zu den BBE-Standorten. Der Norden bekommt ebenfalls Beratung.',
      S.locations,
    ],
    [
      'Wortspiel',
      'Welche Taste schafft zwischen zwei Wörtern Platz?',
      'Leertaste',
      ['Umschalttaste', 'Escape', 'Rücktaste'],
      'Die Leertaste setzt ein Leerzeichen. Raumkonzept in einem Tastendruck.',
    ],
    [
      'Wortspiel',
      'Welcher dieser Sätze kann als Prozentsatz angegeben werden?',
      'Steuersatz',
      ['Hauptsatz', 'Nebensatz', 'Relativsatz'],
      'Der Steuersatz. Hier macht der Satzbau eine kurze Pause.',
    ],
    [
      'Wortspiel',
      'Welche Bank kann im Park stehen, ohne Geld zu verwalten?',
      'Sitzbank',
      ['Zentralbank', 'Investmentbank', 'Genossenschaftsbank'],
      'Die Sitzbank. Ihre wichtigste Anlage ist die Sitzfläche.',
    ],
    [
      'Wortspiel',
      'Welcher Absatz gehört zu einem Schuh?',
      'Der Teil unter der Ferse',
      ['Ein Abschnitt im Text', 'Die verkaufte Menge', 'Eine Leerzeile'],
      'Der Teil unter der Ferse. Nicht jeder Absatz braucht ein Vertriebsmeeting.',
    ],
    [
      'Trivia',
      'Was zeigt ein Thermometer?',
      'Die Temperatur',
      ['Den Luftdruck', 'Die Windrichtung', 'Die Himmelsrichtung'],
      'Die Temperatur. Für die Stimmung im Meeting gibt es noch kein geeichtes Modell.',
    ],
    [
      'Trivia',
      'Welches Gewürz kann einem Gericht deutlich Schärfe geben?',
      'Chili',
      ['Vanille', 'Zimt', 'Muskatblüte'],
      'Chili. Im Curry darf die Argumentation ausnahmsweise brennen.',
    ],
    [
      'Spielwelt',
      'Wie heißt die Figur, die dich in der Spielstory von der Küche zur BBE holt?',
      'Lukas Fleischmann',
      ['Benjamin aus der IT', 'Die Polizeifunkstimme', 'Der Trinkvogel'],
      'Lukas Fleischmann. In dieser Spielgeschichte wird aus Küchenstress ein Karriereangebot.',
    ],
    [
      'Trivia',
      'Was bedeutet das Kürzel WLAN?',
      'Drahtloses lokales Netzwerk',
      [
        'Weltweite Lieferantenabrechnung',
        'Wöchentliche Lohnabrechnung',
        'Wasserleitung am Nebengebäude',
      ],
      'Ein drahtloses lokales Netzwerk. Das Kabel fehlt absichtlich.',
    ],
  ],
  [
    'q07a',
    [
      'BBE',
      'Wofür steht ERFA bei den von BBE moderierten Gruppen?',
      'Erfahrungsaustausch',
      ['Erste Rechnungsfreigabe', 'Elektronische Raumfreigabe', 'Erweiterte Fahranalyse'],
      'Für Erfahrungsaustausch. Andere haben ihre Fehler manchmal schon erfolgreich getestet.',
      S.erfa,
    ],
    [
      'Wortspiel',
      'Welches Schloss öffnet ein Schlüssel, ohne dass man ein Gebäude betritt?',
      'Vorhängeschloss',
      ['Neuschwanstein', 'Nymphenburg', 'Versailles'],
      'Das Vorhängeschloss. Keine Immobilienbesichtigung nötig.',
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet sowohl einen Zeitungstext als auch eine einzelne Ware?',
      'Artikel',
      ['Schlagzeilen', 'Leitglossen', 'Kassenbänder'],
      'Artikel sind Texte und Waren. Hier hat der Handel eine sprachliche Doppelfunktion.',
    ],
    [
      'Wortspiel',
      'Welcher Strich steht sprichwörtlich unter der Rechnung und leitet ein Fazit ein?',
      'Unterm Strich',
      ['Gegen den Strich', 'Auf einen Streich', 'Strich für Strich'],
      'Unterm Strich. Die kürzeste Überleitung zur Schlussfolie.',
    ],
    [
      'Wortspiel',
      'Wer etwas auf die lange Bank schiebt, tut umgangssprachlich was?',
      'Er verschiebt es',
      ['Er bezahlt sofort', 'Er setzt sich hin', 'Er wechselt die Bank'],
      'Er verschiebt es. Das Möbelstück ist in dieser Redewendung unschuldig.',
    ],
    [
      'Trivia',
      'Welches Lebensmittel wird aus Sojabohnen hergestellt?',
      'Tofu',
      ['Couscous', 'Polenta', 'Bulgur'],
      'Tofu entsteht aus Sojabohnen. Eine klare Herkunft ohne Lieferkettenfolie.',
    ],
    [
      'Trivia',
      'Was ist ein Palindrom?',
      'Ein Wort, das vorwärts und rückwärts gleich lautet',
      [
        'Ein Wort mit nur einem Vokal',
        'Ein Ausdruck mit drei Bedeutungen',
        'Eine absichtliche Rechtschreibkorrektur',
      ],
      'Vorwärts wie rückwärts gleich. Hier lohnt sich der Rückblick tatsächlich.',
    ],
    [
      'BBE',
      'Welcher BBE-Produktname klingt nach dem Steuerstand eines Flugzeugs?',
      'Chef-Cockpit PRO',
      ['Chef-Tragfläche PLUS', 'Chef-Düsenjet XL', 'Chef-Landebahn MAX'],
      'Chef-Cockpit PRO ist ein echter Produktname. Eine Pilotenlizenz steht nicht im Namen.',
      S.services,
    ],
    [
      'Trivia',
      'Welches Zeichen trennt in einer E-Mail-Adresse den Namen von der Domain?',
      'Das @-Zeichen',
      ['Das Prozentzeichen', 'Das Gleichheitszeichen', 'Das Paragraphenzeichen'],
      'Das @-Zeichen. Klein, aber für den Verteiler ausgesprochen wichtig.',
    ],
  ],
  [
    [
      'BBE',
      'BBE bietet neben Beratung auch welches Veranstaltungsformat an?',
      'Webinare',
      ['Stierkämpfe', 'Weltraumflüge', 'Hochseeregatten'],
      'Webinare gehören zum Angebot. Lernen ohne Anreise bleibt möglich.',
      S.services,
    ],
    [
      'BBE',
      'Welche Berufsgruppe nennt BBE im Firmenverbund neben Betriebswirten und Immobilienkaufleuten?',
      'Wirtschaftsgeographen',
      ['Versicherungsaktuare', 'Bauphysiker', 'Archäologen'],
      'Wirtschaftsgeographen. Standortwissen hat dort auch fachlich eine gute Adresse.',
      S.group,
    ],
    [
      'Wortspiel',
      'Welches Wort ergänzt Schreib..., ...lampe und ...tennis jeweils zu einem üblichen Wort?',
      'Tisch',
      ['Stuhl', 'Schrank', 'Boden'],
      'Schreibtisch, Tischlampe, Tischtennis. Ein Möbelstück mit erstaunlicher Auslastung.',
    ],
    [
      'Wortspiel',
      'Welche dieser Mäuse braucht keine Nahrung?',
      'Computermaus',
      ['Feldmaus', 'Hausmaus', 'Waldmaus'],
      'Die Computermaus. Der Snack auf dem Schreibtisch ist für jemand anderen.',
    ],
    [
      'Wortspiel',
      'Welche Fliege trägt man zum Anzug am Hals?',
      'Eine gebundene Stoffschleife',
      ['Eine Stubenfliege', 'Eine Schmeißfliege', 'Eine Eintagsfliege'],
      'Die Stoffschleife heißt ebenfalls Fliege. Sie landet hoffentlich nicht in der Suppe.',
    ],
    [
      'Wortspiel',
      'Welche Hülsenfrucht teilt ihren Namen mit einem Bauteil im Kameraobjektiv?',
      'Linse',
      ['Bohne', 'Erbse', 'Kichererbse'],
      'Die Linse. In der Küche macht sie satt, in der Kamera macht sie scharf.',
    ],
    [
      'Trivia',
      'Welcher Fachausdruck bezeichnet die Schriftgestaltung?',
      'Typografie',
      ['Topografie', 'Tomografie', 'Thermografie'],
      'Typografie. Topografie hilft dafür bei der Karte nach dem Meeting.',
    ],
    [
      'BBE',
      'Mit welchem Bild beschreibt BBE den kurzen Weg zu zusätzlichem Wissen im Firmenverbund?',
      'Einfach nach nebenan gehen',
      ['Im Archiv überwintern', 'Die Branche wechseln', 'Ein Konkurrenzunternehmen kaufen'],
      'BBE beschreibt den Verbund mit dem Gang nach nebenan. Wissen hat dort kurze Wege.',
      S.group,
    ],
    [
      'Trivia',
      'Welcher Kamerabegriff bezeichnet eine Änderung der Brennweite, durch die Objekte im Bild größer erscheinen können?',
      'Zoom',
      ['Echo', 'Loop', 'Stummfilm'],
      'Zoom. Bei Folien manchmal die letzte Rettung für zu kleine Schrift.',
    ],
    [
      'Spielwelt',
      'Was wird im Maßkrug-Minispiel der Brauerei möglichst lange gehalten?',
      'Ein Maßkrug',
      ['Ein Whiteboard', 'Eine Parkuhr', 'Ein Drucker'],
      'Ein Maßkrug. Ausdauer wird hier nicht an der Länge einer Sitzung gemessen.',
    ],
  ],
  [
    [
      'BBE',
      'Welche deutsche Großstadt führt BBE als Standort in der Hubertusallee?',
      'Berlin',
      ['Bremen', 'Dresden', 'Dortmund'],
      'Berlin. Die Hubertusallee steht im offiziellen Standortverzeichnis.',
      S.locations,
    ],
    [
      'BBE',
      'Was besucht BBE in der ersten Folge der Retail Scouts von 2022?',
      'Ein Erlebniskaufhaus in Gotha',
      [
        'Einen Wochenmarkt in Leipzig',
        'Ein Shoppingcenter in Berlin',
        'Eine Fußgängerzone in Köln',
      ],
      'Die erste Folge besucht das Erlebnishaus Moses in Gotha. Retail-Wissen auf Reisen.',
      S.scouts,
    ],
    [
      'Wortspiel',
      'Welches Wort ergänzt Daten..., ...konto und ...überfall?',
      'Bank',
      ['Kasse', 'Tisch', 'Karte'],
      'Datenbank, Bankkonto, Banküberfall. Nur eines davon gehört ins IT-Konzept.',
    ],
    [
      'Wortspiel',
      'Welches Wort kann eine Handlung beim Schach, einen Bahnverband und einen Schluck bezeichnen?',
      'Zug',
      ['Takt', 'Gleis', 'Gang'],
      'Ein Zug. Die Sprache fährt hier auf mehreren Gleisen.',
    ],
    [
      'Wortspiel',
      'Die Autofahrerin umfuhr das Hindernis; danach stand es noch unbeschädigt. Was tat sie?',
      'Sie fuhr darum herum',
      ['Sie fuhr es zu Boden', 'Sie lud es ins Auto', 'Sie ersetzte es durch ein Schild'],
      'Sie fuhr darum herum. Der Zusatz klärt die Doppelbedeutung von umfahren.',
    ],
    [
      'Wortspiel',
      'Welches Wort bedeutet ein Dokument und zugleich etwas, das man für seine Aussage anführen kann?',
      'Beleg',
      ['Belag', 'Belang', 'Beilage'],
      'Ein Beleg. Der Kassenzettel bekommt kurz eine wissenschaftliche Karriere.',
    ],
    [
      'Trivia',
      'Was beschreibt die Topografie?',
      'Die Gestalt einer Landschaft',
      ['Die Gestaltung von Schrift', 'Die Lautstärke eines Tons', 'Die Reihenfolge von Buchungen'],
      'Die Gestalt einer Landschaft. Ein anderer Zuständigkeitsbereich als die Typografie.',
    ],
    [
      'BBE',
      'Für welche Stadt veröffentlichte BBE 2026 ein Whitepaper zum Thema Markthalle?',
      'Hamburg',
      ['Köln', 'Erfurt', 'Berlin'],
      'Das Whitepaper widmet sich einer Markthalle für Hamburg. Retail-Wissen mit Appetit.',
      S.publications,
    ],
    [
      'Trivia',
      'Welches dieser Wörter bezeichnet ein absichtlich neues Wort?',
      'Neologismus',
      ['Palindrom', 'Synonym', 'Antonym'],
      'Ein Neologismus ist eine Wortneuschöpfung. Auch der Quizssoir hat sprachlich neu eröffnet.',
    ],
    [
      'Trivia',
      'Welches Satzzeichen kann einen ausgelassenen Buchstaben markieren, etwa in geht’s?',
      'Apostroph',
      ['Doppelpunkt', 'Semikolon', 'Bindestrich'],
      'Der Apostroph markiert hier die Auslassung. Ein kleines Zeichen spart einen Buchstaben.',
    ],
  ],
  [
    [
      'BBE',
      'Welche BBE-Publikationsreihe hat Ausgaben wie Möbel 2026 oder Schuhe 2026?',
      'Branchenberichte',
      ['Standortsteckbriefe', 'ERFA-Protokolle', 'Mitarbeiterbefragungen'],
      'Branchenberichte widmen sich einzelnen Märkten. Schuhe und Möbel bekommen eigene Kapitel.',
      S.publications,
    ],
    [
      'BBE',
      'Welche Eigenschaft betont BBE für die Unternehmen einer ERFA-Gruppe?',
      'Sie stehen nicht in direktem Wettbewerb',
      [
        'Sie besitzen alle dieselbe Filiale',
        'Sie verkaufen ausschließlich online',
        'Sie haben alle denselben Geschäftsführer',
      ],
      'Laut BBE sollen die Firmen einer Gruppe keine direkten Wettbewerber sein.',
      S.erfa,
    ],
    [
      'Wortspiel',
      'Welches Wort kann sowohl ein Verzeichnis als auch einen Finger bezeichnen?',
      'Index',
      ['Glossar', 'Kapitel', 'Anhang'],
      'Index bezeichnet ein Verzeichnis und medizinisch den Zeigefinger. Gute Orientierung in beiden Fällen.',
      S.index,
    ],
    [
      'Wortspiel',
      'Welche Schreibweise ergibt vorwärts und rückwärts dasselbe Wort?',
      'Lagerregal',
      ['Lagerhalle', 'Aktenregal', 'Regalbrett'],
      'Lagerregal ist ein Palindrom. Sogar das Lager kann sich hier rückwärts lesen.',
    ],
    [
      'Wortspiel',
      'Welche Wendung bedeutet, ein Thema gezielt anzusprechen?',
      'Etwas aufs Tapet bringen',
      ['Etwas unter den Teppich kehren', 'Etwas auf Eis legen', 'Etwas ad acta legen'],
      'Etwas aufs Tapet bringen heißt, es zum Gesprächsgegenstand zu machen.',
    ],
    [
      'Wortspiel',
      'Welches Verb kann sowohl über einen Ort fliegen als auch einen Text schnell lesen bedeuten?',
      'Überfliegen',
      ['Abheben', 'Einchecken', 'Zwischenlanden'],
      'Man kann eine Landschaft und einen Text überfliegen. Nur eines davon braucht Flughöhe.',
    ],
    [
      'Wortspiel',
      'Welches Wort ergänzt Tagesordnungs..., ...landung und ...abzug jeweils zu einem geläufigen Wort?',
      'Punkt',
      ['Plan', 'Zeit', 'Kurs'],
      'Tagesordnungspunkt, Punktlandung, Punktabzug. Für einmal passt alles auf den Punkt.',
    ],
    [
      'BBE',
      'Welche BBE-Niederlassung liegt laut Standortverzeichnis in der Futterstraße?',
      'Erfurt',
      ['Essen', 'Bonn', 'Kiel'],
      'Erfurt. Die Futterstraße ist eine echte Adresse, kein interner Name für die Mittagspause.',
      S.locations,
    ],
    [
      'Trivia',
      'Was ist ein Anagramm?',
      'Ein Wort aus umgestellten Buchstaben eines anderen',
      [
        'Ein Wort mit gegensätzlicher Bedeutung',
        'Eine Abkürzung aus Anfangsbuchstaben',
        'Ein Wort ohne Vokale',
      ],
      'Bei einem Anagramm werden dieselben Buchstaben neu angeordnet. Reorganisation im Kleinformat.',
    ],
    [
      'BBE',
      'Welches Themenpaar verbindet der Firmenverbund von BBE und IPH besonders?',
      'Einzelhandel und Handelsimmobilien',
      [
        'Tourismus und Veranstaltungsstätten',
        'Industrie und Produktionsanlagen',
        'Versicherungen und Wohnungsbau',
      ],
      'Einzelhandel und Handelsimmobilien gehören im Verbund zusammen.',
      S.group,
    ],
  ],
  [
    'v2-11b',
    'v2-11c',
    'v2-11d',
    'v2-11f',
    'v2-11g',
    'v2-11i',
    'v2-11j',
    [
      'Knobelei',
      'Eine Box enthält nur Stifte, eine nur Kabel, eine beides. Alle Etiketten sind falsch. Aus welcher beschrifteten Box genügt ein gezogenes Teil zum Zuordnen aller Boxen?',
      'Aus Gemischt',
      ['Aus Stifte', 'Aus Kabel', 'Aus keiner einzelnen Box'],
      'Gemischt muss sortenrein sein. Der gezogene Gegenstand legt diese Box fest; die beiden übrigen folgen aus den falschen Etiketten.',
    ],
    [
      'Knobelei',
      'Alle roten Mappen sind freigegeben. Keine vertrauliche Mappe ist freigegeben. Einige rote Mappen sind gedruckt. Was folgt sicher?',
      'Einige gedruckte Mappen sind nicht vertraulich',
      [
        'Alle gedruckten Mappen sind rot',
        'Keine blaue Mappe ist freigegeben',
        'Alle nicht vertraulichen Mappen sind gedruckt',
      ],
      'Die gedruckten roten Mappen sind freigegeben und deshalb nicht vertraulich. Über andere Mappen wissen wir nichts.',
    ],
    [
      'Knobelei',
      'Ein Mann ohne Geschwister zeigt ein Foto: Der Vater dieser Person ist der Sohn meines Vaters. Wen zeigt das Foto?',
      'Sein eigenes Kind',
      ['Seinen Vater', 'Sich selbst', 'Seinen Großvater'],
      'Der Sohn seines Vaters ist er selbst. Die Person auf dem Foto ist also sein Kind. Familienstruktur ohne Organigramm.',
    ],
  ],
  [
    'v2-12a',
    'v2-12b',
    'v2-12c',
    'v2-12d',
    'v2-12e',
    'v2-12h',
    'v2-12i',
    [
      'Knobelei',
      'Fünf Ordner stehen in einer Reihe: B direkt rechts von D, A direkt links von C, E ganz rechts. C steht links von D. Welcher Ordner steht in der Mitte?',
      'D',
      ['A', 'B', 'C'],
      'Die einzige Reihenfolge ist A, C, D, B, E. Damit steht D in der Mitte. Endlich eindeutige Ablage.',
    ],
    [
      'Knobelei',
      'In einer dunklen Schublade liegen rote und blaue Stifte, mindestens zehn pro Farbe. Wie viele musst du blind mindestens ziehen, um sicher drei derselben Farbe zu haben?',
      'Fünf',
      ['Drei', 'Vier', 'Sechs'],
      'Vier könnten zwei rote und zwei blaue sein. Der fünfte ergänzt sicher eine Farbe zum Dreierteam.',
    ],
    [
      'Knobelei',
      'Nur mit Karte A darf man ins Archiv. Nicht jeder mit Karte A hat Karte B. Kim ist berechtigt im Archiv. Welche Aussage ist sicher?',
      'Kim hat A; über B ist nichts sicher',
      ['Kim hat beide Karten', 'Kim hat A, aber nicht B', 'Kim hat B, aber nicht A'],
      'A ist für den Zutritt notwendig. Die Aussage über B betrifft die Gruppe und entscheidet nichts über Kim.',
    ],
  ],
  [
    'v2-13a',
    'v2-13b',
    'v2-13c',
    'v2-13d',
    'v2-13e',
    'v2-13g',
    'v2-13j',
    [
      'Knobelei',
      'Zwei Wächter kennen den Ausgang: einer lügt immer, einer sagt immer die Wahrheit. Welche Frage an einen von ihnen zeigt bei zwei Türen sicher die falsche Tür?',
      'Welche Tür würde der andere als Ausgang nennen?',
      [
        'Welche Tür ist der Ausgang?',
        'Bist du der ehrliche Wächter?',
        'Stehst du vor dem Ausgang?',
      ],
      'Der Ehrliche berichtet die Lüge, der Lügner verdreht die Wahrheit. Beide zeigen so auf die falsche Tür. Du nimmst die andere.',
    ],
    [
      'Knobelei',
      'Vier Ordner stehen nebeneinander. D steht ganz links. A steht nicht am Rand. B steht rechts von A. C steht nicht neben B. Wer steht an zweiter Stelle?',
      'C',
      ['A', 'B', 'D'],
      'Nur D, C, A, B erfüllt alles. A auf Platz zwei würde C neben B zwingen.',
    ],
    [
      'Knobelei',
      'Eine Liste enthält genau zwei Aussagen: Erstens: Beide Aussagen dieser Liste sind falsch. Zweitens: Genau eine Aussage dieser Liste ist falsch. Was stimmt?',
      'Nur die zweite Aussage ist wahr',
      ['Nur die erste Aussage ist wahr', 'Beide Aussagen sind wahr', 'Beide Aussagen sind falsch'],
      'Die erste kann nicht wahr sein, sonst wäre sie selbst falsch. Damit ist genau eine Aussage falsch und die zweite wahr.',
    ],
  ],
  [
    'v2-14a',
    'v2-14b',
    'v2-14c',
    'v2-14d',
    'v2-14e',
    'v2-14h',
    'v2-14i',
    [
      'Knobelei',
      'Drei Schubladen haben Aufschriften: A: Der Schlüssel liegt in B. B: Er liegt nicht in B. C: Er liegt nicht in A. Genau eine Aufschrift ist wahr. Wo liegt der Schlüssel?',
      'In A',
      ['In B', 'In C', 'Außerhalb aller drei Schubladen'],
      'A und B widersprechen einander, also ist genau eine davon wahr. C muss falsch sein: Der Schlüssel liegt in A.',
    ],
    [
      'Knobelei',
      'Vier Personen mit einer Lampe starten gemeinsam: Sie brauchen 1, 2, 7 und 10 Minuten über eine Brücke. Maximal zwei gehen zusammen; die Lampe muss mit, das langsamere Tempo gilt. Wann sind frühestens alle drüben?',
      '17 Minuten',
      ['15 Minuten', '19 Minuten', '22 Minuten'],
      '1 und 2 gehen hin, 1 zurück; 7 und 10 hin, 2 zurück; 1 und 2 hin. Die Zeiten 2, 1, 10, 2 und 2 ergeben 17.',
    ],
    [
      'Knobelei',
      'Ein Preis liegt in einer von drei Schachteln. Alle Aufschriften sind falsch: A sagt Nicht in A, B sagt In A, C sagt Nicht in B. Wo liegt der Preis?',
      'Keine Lösung möglich',
      ['In A', 'In B', 'In C'],
      'A würde als falsche Aussage den Preis in A erzwingen. B wäre dann aber wahr. Die Vorgaben widersprechen sich. Auch ein Briefing kann unlösbar sein.',
    ],
  ],
  [
    'v2-15a',
    'v2-15b',
    'v2-15c',
    'v2-15d',
    'v2-15f',
    'v2-15i',
    'v2-15j',
    [
      'Knobelei',
      'Vier Karten zeigen A, D, 4 und 7. Jede hat auf einer Seite einen Buchstaben, auf der anderen eine Zahl. Regel: Hinter jedem Vokal steht eine gerade Zahl. Welche Karten musst du mindestens umdrehen?',
      'A und 7',
      ['A und 4', 'Nur A', 'D und 4'],
      'A darf keine ungerade Rückseite haben, hinter 7 darf kein Vokal stehen. Die 4 muss keinen Vokal tragen; über D sagt die Regel nichts.',
    ],
    [
      'Knobelei',
      'A sagt: B lügt. B sagt: C lügt. C sagt: A und B lügen beide. Jede Person sagt entweder die Wahrheit oder lügt. Wer sagt die Wahrheit?',
      'Nur B',
      ['Nur A', 'Nur C', 'A und C'],
      'B ist wahr, C und A sind falsch. Jede andere Zuordnung widerspricht mindestens einer Aussage.',
    ],
    [
      'Knobelei',
      'Ein dreistelliger Code verwendet verschiedene Ziffern. Jede Tabellenzeile nennt alle Treffer; die übrigen Ziffern kommen nicht vor. Welcher Code passt?',
      '042',
      ['062', '402', '204'],
      '738 schließt 7, 3 und 8 aus. 6 widerspräche den ersten beiden Hinweisen; deshalb steht 2 hinten. Aus 206 folgt 0 vorn, aus 614 die 4 in der Mitte.',
      {
        visual: {
          type: 'table',
          title: 'Hinweise zum Zahlenschloss',
          columns: ['Versuch', 'Treffer'],
          rows: [
            ['682', '1 richtig und am richtigen Platz'],
            ['614', '1 richtig, aber am falschen Platz'],
            ['206', '2 richtig, beide am falschen Platz'],
            ['738', 'Keine Ziffer richtig'],
          ],
        },
      },
    ],
  ],
];

export function buildTriviaQuestions(legacy, previous, makeQuestion, freezeTree) {
  const originals = new Map([...legacy, ...previous].map((question) => [question.id, question]));
  return Object.freeze(
    TRIVIA_TIERS.flatMap((tier, index) => {
      const level = index + 1;
      if (tier.length !== 10) throw new Error('Quizssoir: each trivia level needs ten questions');
      return tier.map((entry, position) => {
        if (typeof entry === 'string') {
          const original = originals.get(entry);
          if (!original || original.level !== level)
            throw new Error('Quizssoir: invalid immutable question reference ' + entry);
          return original;
        }
        const [category, text, answer, others, explanation, reference = null] = entry;
        const meta = reference && typeof reference === 'object' ? reference : { source: reference };
        const id = 'v3-' + String(level).padStart(2, '0') + String.fromCharCode(97 + position);
        return freezeTree({
          ...makeQuestion(
            id,
            level,
            category,
            text,
            answer,
            others,
            explanation,
            meta.source || null,
          ),
          visual: meta.visual || null,
          discovery: null,
        });
      });
    }),
  );
}
