// Quizssoir 4: real BBE knowledge and objective language play from round one.
// All real-company claims were checked on the official linked pages, 2026-10-02.
// No fictional colleague, game event or unstable employee/project count is used.
export const QUIZ_BBE_SOURCES = Object.freeze({
  address: 'https://www.bbe.de/de/impressum/',
  company: 'https://www.bbe.de/de/uber-uns/',
  services: 'https://www.bbe.de/de/leistungen/',
  contact: 'https://www.bbe.de/de/kontakt/',
  publications: 'https://www.bbe.de/de/aktuelles/',
  seminars: 'https://www.bbe.de/de/leistungen/vortrage-seminare/',
  teaching: 'https://www.bbe.de/de/leistungen/vortrage-seminare/lehrtatigkeit/',
  municipal: 'https://www.bbe.de/de/leistungen/kommunalberatung/',
  locations: 'https://www.bbe.de/de/kontakt/standorte/',
  research: 'https://www.bbe.de/de/leistungen/marktforschung-daten/',
  frequency: 'https://www.bbe.de/de/leistungen/marktforschung-daten/frequenzanalysen/',
  employees:
    'https://www.bbe.de/de/leistungen/marktforschung-daten/mitarbeiter-zufriedenheitsanalysen/',
  location: 'https://www.bbe.de/de/leistungen/standortberatung/',
  group: 'https://www.bbe.de/de/uber-uns/firmenverbund/',
  erfa: 'https://www.bbe.de/de/leistungen/managementberatung/erfa-erfahrungsaustausch/',
  chefplan: 'https://www.bbe.de/de/leistungen/produkte-tools/chefplan/',
  mystery: 'https://www.bbe.de/de/leistungen/marktforschung-daten/testkaufe-mystery-shopping/',
  ekpro: 'https://www.bbe.de/de/leistungen/produkte-tools/ek-pro/',
  pep: 'https://www.bbe.de/de/leistungen/produkte-tools/pepinternet/',
  liquid: 'https://www.bbe.de/de/leistungen/produkte-tools/liquiditaetscockpit/',
  pos: 'https://www.bbe.de/de/leistungen/produkte-tools/pos-navigator/',
  skpro: 'https://www.bbe.de/de/leistungen/produkte-tools/sk-pro/',
  succession: 'https://www.bbe.de/de/leistungen/managementberatung/grundung-nachfolge-bewertung/',
  diligence: 'https://www.bbe.de/de/leistungen/immobilienberatung/ankaufsprufung-due-diligence/',
  property: 'https://www.bbe.de/de/leistungen/immobilienberatung/',
});
const S = QUIZ_BBE_SOURCES;

// Strings reuse immutable records, on exactly their original level. A newly
// worded or moved question always receives a fresh v4 ID in the builder below.
const BBE_TIERS = [
  [
    'q01a',
    [
      'BBE',
      'Welches Wort vervollständigt den Firmennamen BBE ... GmbH?',
      'Handelsberatung',
      ['Hochseefischerei', 'Haarverlängerung', 'Hubschraubervermietung'],
      'Handelsberatung. Der Name verrät mehr als manche Titelfolie.',
      S.address,
    ],
    [
      'BBE',
      'Was bietet die BBE-Website für eine schriftliche Anfrage direkt im Browser an?',
      'Ein Kontaktformular',
      ['Einen Lottoschein', 'Ein Kreuzworträtsel', 'Eine Parkscheibe'],
      'Ein Kontaktformular. Der erste Kontakt braucht keine Brieftaube.',
      S.contact,
    ],
    [
      'BBE',
      'Was vermitteln BBE-Experten in ihren öffentlichen Vorträgen und Seminaren?',
      'Fachwissen',
      ['Führerscheine', 'Opernkostüme', 'Tauchabzeichen'],
      'Fachwissen. Eine seltene Gelegenheit, bei der Zuhören ausdrücklich die Aufgabe ist.',
      S.seminars,
    ],
    [
      'BBE',
      'Was veröffentlicht BBE zu Handelsmärkten?',
      'Studien und Branchenberichte',
      ['Kriminalromane', 'Malbücher für Haustiere', 'Sternzeichenkalender'],
      'Studien und Branchenberichte. Spannung geht auch mit belastbaren Quellen.',
      S.publications,
    ],
    [
      'Wortspiel',
      'Welche Kunden zählen zur Laufkundschaft, auch ohne Jogginghose?',
      'Spontan vorbeikommende Kunden',
      ['Ausschließlich Marathonläufer', 'Nur Sporttrainer', 'Nur Laufbandhersteller'],
      'Spontan vorbeikommende Kunden. Der Weg ins Geschäft ist kein Fitnesstest.',
    ],
    [
      'Wortspiel',
      'Welche Maus braucht im Büro kein Futter?',
      'Computermaus',
      ['Hausmaus', 'Feldmaus', 'Waldmaus'],
      'Die Computermaus. Die Kekse auf dem Schreibtisch sind für jemand anderen.',
    ],
    [
      'Wortspiel',
      'Was ist ein Ladenhüter, obwohl er keine Nachtwache hält?',
      'Eine schwer verkäufliche Ware',
      ['Ein Wachmann im Geschäft', 'Ein besonders treuer Kunde', 'Ein Türschloss am Eingang'],
      'Eine schwer verkäufliche Ware. Sie bleibt lange, aber nicht aus Pflichtgefühl.',
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet sowohl einen Laden als auch eine abgeschlossene Handelstransaktion?',
      'Geschäft',
      ['Schaufenster', 'Kassenbon', 'Lieferwagen'],
      'Geschäft. Man kann eines betreten und eines abschließen, ohne die Tür zu bewegen.',
    ],
    [
      'Wortspiel',
      'Welches Fenster schließt man per Klick und ohne Fenstergriff?',
      'Programmfenster',
      ['Dachfenster', 'Kellerfenster', 'Schaufenster'],
      'Das Programmfenster. Zum Stoßlüften taugt es leider nicht.',
    ],
  ],
  [
    'q02a',
    'v3-02e',
    [
      'BBE',
      'Wie heißt der BBE-Bereich für Städte und Gemeinden?',
      'Kommunalberatung',
      ['Kommunalfrisur', 'Kometenberatung', 'Kommodenbau'],
      'Kommunalberatung. Hier bekommt die Stadt ein Konzept statt eines neuen Haarschnitts.',
      S.municipal,
    ],
    [
      'BBE',
      'In welcher Form kann man einen BBE-Fachvortrag auch online besuchen?',
      'Als Webinar',
      ['Als Briefmarke', 'Als Warenprobe', 'Als Parkticket'],
      'Als Webinar. Die Anreise endet am eigenen Bildschirm.',
      S.seminars,
    ],
    [
      'BBE',
      'Welche dieser Hafenstädte nennt BBE als eigenen Standort?',
      'Hamburg',
      ['Rotterdam', 'Genua', 'Marseille'],
      'Hamburg. Die Beratung hat auch im Norden eine Adresse.',
      S.locations,
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet einen Teil unter der Ferse und einen Abschnitt im Text?',
      'Absatz',
      ['Kragen', 'Kapitel', 'Sohle'],
      'Absatz. Ein abgebrochener Absatz ist deshalb nicht immer ein Schreibproblem.',
    ],
    [
      'Wortspiel',
      'Welcher dieser Sätze wird häufig in Prozent angegeben?',
      'Steuersatz',
      ['Hauptsatz', 'Nebensatz', 'Relativsatz'],
      'Der Steuersatz. Hier wechselt der Satzbau kurz in die Buchhaltung.',
    ],
    [
      'Wortspiel',
      'Welche Bank bietet im Park eine Sitzfläche statt eines Kontos?',
      'Sitzbank',
      ['Zentralbank', 'Investmentbank', 'Genossenschaftsbank'],
      'Die Sitzbank. Ihre wichtigste Anlage ist die Sitzfläche.',
    ],
    [
      'Wortspiel',
      'Welche Zweige eines Unternehmens haben Geschäftsräume statt Blätter?',
      'Zweigstellen',
      ['Tannenzweige', 'Weidenzweige', 'Misteln'],
      'Zweigstellen. Unternehmenswachstum kommt häufig ohne Gießkanne aus.',
    ],
    [
      'Wortspiel',
      'Welchen Auszug liefert die Bank, ohne dass jemand umzieht?',
      'Kontoauszug',
      ['Wohnungsauszug', 'Möbelauszug', 'Küchenauszug'],
      'Den Kontoauszug. Die Zahlen ziehen ein, die Möbel bleiben stehen.',
    ],
  ],
  [
    'q03a',
    'v3-03j',
    [
      'BBE',
      'Wen lässt BBE bei Kundenbefragungen selbst zu Wort kommen?',
      'Kundinnen und Kunden',
      ['Nur die Hausmeister', 'Nur die Lieferwagenfahrer', 'Ausschließlich Wettbewerber'],
      'Kundinnen und Kunden. Die Zielgruppe darf ihre Meinung ausnahmsweise selbst formulieren.',
      S.research,
    ],
    [
      'BBE',
      'Wessen Zufriedenheit untersucht BBE mit einem eigenen Analyseangebot neben der Kundenzufriedenheit?',
      'Die der Mitarbeitenden',
      ['Die der Büropflanzen', 'Die der Paketaufkleber', 'Die der Parkautomaten'],
      'Die der Mitarbeitenden. Auch das Team bekommt Gehör, nicht nur der Markt.',
      S.employees,
    ],
    [
      'BBE',
      'Wie beschreibt BBE die Reichweite ihrer Kundenbeziehungen?',
      'Regional, national und international',
      [
        'Ausschließlich innerhalb Münchens',
        'Nur im eigenen Bürogebäude',
        'Nur innerhalb derselben Straße',
      ],
      'Regional, national und international. Der Horizont endet nicht am nächsten Straßenschild.',
      S.company,
    ],
    [
      'Wortspiel',
      'Welcher Umschlag wird frankiert statt als Warenbewegung erfasst?',
      'Briefumschlag',
      ['Lagerumschlag', 'Kapitalumschlag', 'Wetterumschlag'],
      'Der Briefumschlag. Hier gehört die Marke tatsächlich außen drauf.',
    ],
    [
      'Wortspiel',
      'Welcher Schalter kann mit einer Person besetzt sein, statt das Licht zu schalten?',
      'Bankschalter',
      ['Kippschalter', 'Lichtschalter', 'Drehschalter'],
      'Der Bankschalter. Bitte trotzdem nicht einfach auf die Person drücken.',
    ],
    [
      'Wortspiel',
      'Ein Redner hat viel Anhang. Wer ist gemeint, wenn es nicht um seine E-Mails geht?',
      'Seine Unterstützer',
      ['Seine PDF-Dateien', 'Seine Fußnoten', 'Seine Druckerpatronen'],
      'Seine Unterstützer. Dieser Anhang lässt sich nicht einfach als ZIP-Datei verschicken.',
    ],
    [
      'Wortspiel',
      'Welchen Auftrag kann ein Maler mit dem Pinsel verteilen?',
      'Farbauftrag',
      ['Zahlungsauftrag', 'Speditionsauftrag', 'Kundenauftrag'],
      'Den Farbauftrag. Der Kundenauftrag war schon vorher erteilt.',
    ],
    [
      'Wortspiel',
      'Welche Führung erklärt eine Ausstellung, statt ein Team zu leiten?',
      'Museumsführung',
      ['Unternehmensführung', 'Abteilungsleitung', 'Geschäftsführung'],
      'Die Museumsführung. Hier ist der Blick zurück ausdrücklich erwünscht.',
    ],
  ],
  [
    'q04a',
    'v3-04g',
    [
      'BBE',
      'Wo vermitteln BBE-Experten ihr Wissen laut dem Angebot Lehrtätigkeit ebenfalls?',
      'An Hochschulen und Akademien',
      ['Nur in Fahrschulen', 'Nur in Musikschulen', 'Nur in Hundeschulen'],
      'An Hochschulen und Akademien. Handelswissen schafft es also auch in den Hörsaal.',
      S.teaching,
    ],
    [
      'BBE',
      'Welche Kundengruppe nennt BBE neben Handel, Kommunen und Immobilienwirtschaft?',
      'Industrie',
      ['Raumfahrer', 'Zauberlehrlinge', 'Rennpferde'],
      'Die Industrie gehört zum genannten Kundenkreis. Der Blick reicht damit auch hinter das Verkaufsregal.',
      S.company,
    ],
    [
      'BBE',
      'Welche Einstiegsmöglichkeit erwähnt BBE auf ihrer Über-uns-Seite ausdrücklich?',
      'Praktikant',
      ['Testpilot', 'Schiffsjunge', 'Opernsolist'],
      'Praktikant. Jede Karriere darf mit mehr Neugier als Visitenkarten beginnen.',
      S.company,
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet sowohl eine Handelsveranstaltung als auch einen Gottesdienst?',
      'Messe',
      ['Börse', 'Tagung', 'Konferenz'],
      'Messe. Der Zusammenhang entscheidet, ob Aussteller oder Altar gemeint sind.',
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet ein Geschäft und als Verb das Füllen eines Akkus?',
      'Laden',
      ['Kaufen', 'Leeren', 'Packen'],
      'Laden. Ein voller Laden und ein voller Akku sind dennoch verschiedene Kennzahlen.',
    ],
    [
      'Wortspiel',
      'Welcher Kurs gehört zur Preisnotierung einer Aktie statt zum Stundenplan?',
      'Börsenkurs',
      ['Sprachkurs', 'Schwimmkurs', 'Tanzkurs'],
      'Der Börsenkurs. Er kann fallen, ohne dass jemand die Prüfung nicht besteht.',
    ],
    [
      'Wortspiel',
      'Im Meeting will jemand andere Saiten aufziehen. Was kündigt die Redewendung an?',
      'Ein strengeres Vorgehen',
      ['Eine neue Gitarrenstimmung', 'Eine andere Seitenzahl', 'Eine höhere Bildschirmauflösung'],
      'Ein strengeres Vorgehen. Das Instrument bleibt dabei im Koffer.',
    ],
    [
      'Wortspiel',
      'Wie heißt sowohl der Absenderblock unter einer E-Mail als auch ein Namenszeichen auf einem Gemälde?',
      'Signatur',
      ['Betreff', 'Postleitzahl', 'Seitenzahl'],
      'Signatur. Sie verrät, wer dahintersteht; die Handschrift darf unterschiedlich sein.',
    ],
  ],
  [
    'q05a',
    'v3-05g',
    [
      'BBE',
      'Was betont BBE bei ihrer Rolle als reiner Dienstleister?',
      'Neutralität und Unabhängigkeit',
      ['Eine eigene Ladenkette', 'Exklusive Warenproduktion', 'Einen festen staatlichen Auftrag'],
      'Neutralität und Unabhängigkeit. Die Empfehlung soll auf Wissen stehen, nicht auf Eigenverkauf.',
      S.company,
    ],
    [
      'BBE',
      'Welches BBE-Angebot beschäftigt sich damit, Einkäufe des Alltags in der Nähe zu ermöglichen?',
      'Nahversorgungskonzepte',
      ['Fernreiseplanung', 'Fernsehprogrammplanung', 'Nachtsichtgeräte'],
      'Nahversorgungskonzepte. Gute Versorgung beginnt manchmal mit einem kurzen Weg.',
      S.municipal,
    ],
    [
      'BBE',
      'Welches Netz optimiert BBE mit Filialnetzoptimierung?',
      'Ein Netz aus Geschäftsstandorten',
      ['Ein Volleyballnetz', 'Ein Fischernetz', 'Ein WLAN-Passwort'],
      'Das Netz der Geschäftsstandorte. Router und Angel bleiben in anderen Zuständigkeitsbereichen.',
      S.location,
    ],
    [
      'Wortspiel',
      'Welcher Posten steht in einer Rechnung statt bei der Wachmannschaft?',
      'Rechnungsposten',
      ['Wachposten', 'Spähposten', 'Grenzposten'],
      'Der Rechnungsposten. Er muss stimmen, aber nicht strammstehen.',
    ],
    [
      'Wortspiel',
      'Welcher Druck beschreibt knappe Zeit statt Farbe auf Papier?',
      'Zeitdruck',
      ['Buchdruck', 'Offsetdruck', 'Siebdruck'],
      'Zeitdruck. Ein Problem, das sich leider nicht durch Nachfüllen von Toner löst.',
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet sowohl eine Aufgabe im Team als auch aufgewickeltes Papier?',
      'Rolle',
      ['Rang', 'Posten', 'Stapel'],
      'Rolle. Manchmal braucht die neue Rolle eine Einarbeitung, manchmal nur eine Halterung.',
    ],
    [
      'Wortspiel',
      'Welcher Sitz bezeichnet den offiziellen Ort eines Unternehmens?',
      'Firmensitz',
      ['Autositz', 'Hochsitz', 'Rücksitz'],
      'Der Firmensitz. Eine gute Polsterung gehört nicht zur Definition.',
    ],
    [
      'Wortspiel',
      'Was bildet ein finanzielles Polster, ohne eine Matratze zu sein?',
      'Rücklage',
      ['Rückenlage', 'Sitzauflage', 'Bettauflage'],
      'Eine Rücklage. Gut gepolstert ist manchmal eine Frage des Kontos.',
    ],
  ],
  [
    'v3-06a',
    [
      'BBE',
      'Was behält man mit dem BBE Chefplan im Blick, ohne dem Chef hinterherzulaufen?',
      'Betriebszahlen und Planabweichungen',
      [
        'Seine privaten Reiserouten',
        'Die Sitzordnung bei Kongressen',
        'Die Öffnungszeiten der Kantine',
      ],
      'Betriebszahlen und Planabweichungen. Der Chefplan verfolgt die Entwicklung des Geschäfts.',
      S.chefplan,
    ],
    [
      'BBE',
      'Welche reale BBE-Leistung prüft den Service durch Testkäufe mit zunächst unerkannten Testkunden?',
      'Mystery-Shopping',
      ['Schaufensterdekoration', 'Wareninventur', 'Lieferantenbuchhaltung'],
      'Mystery-Shopping. Das Geheimnis ist der Testauftrag, nicht der Inhalt des Warenkorbs.',
      S.mystery,
    ],
    [
      'BBE',
      'Was zählt BBE bei Frequenzanalysen an einem Einkaufsstandort statt Radiowellen?',
      'Passanten beziehungsweise Besucher',
      ['Sendemasten pro Sender', 'Schwingungen einer Stimmgabel', 'Megahertz im Autoradio'],
      'Passanten beziehungsweise Besucher. Frequenz bedeutet hier Bewegung am Standort.',
      S.frequency,
    ],
    [
      'BBE',
      'Wobei begleitet BBE Unternehmen im Leistungsbereich Nachfolge?',
      'Bei der Übergabe eines Unternehmens',
      [
        'Bei der Verfolgung von Paketen',
        'Beim Sammeln neuer Social-Media-Follower',
        'Bei der Reihenfolge im Pausenraum',
      ],
      'Bei der Unternehmensübergabe. Nachfolge heißt hier Verantwortung weitergeben.',
      S.succession,
    ],
    [
      'Wortspiel',
      'Welches Wort bezeichnet einen Geldbeutel und einen organisierten Handelsplatz?',
      'Börse',
      ['Tresor', 'Kasse', 'Depot'],
      'Börse. Eine passt in die Tasche, die andere organisiert den Handel.',
    ],
    [
      'Wortspiel',
      'Welches Wort kann einen Zuschlag zum Preis und den ersten Schlag beim Tennis bezeichnen?',
      'Aufschlag',
      ['Abschreibung', 'Anschaffung', 'Angebot'],
      'Aufschlag. Im Handel muss dafür niemand über ein Netz schlagen.',
    ],
    [
      'Wortspiel',
      'Welche Blüten wären an der Ladenkasse ein Fall für die Polizei statt für den Floristen?',
      'Gefälschte Banknoten',
      ['Rosenblüten', 'Orchideenblüten', 'Kirschblüten'],
      'Gefälschte Banknoten heißen umgangssprachlich Blüten. Gießen verbessert ihren Wert nicht.',
    ],
    [
      'Wortspiel',
      'Welche Spanne bezeichnet im Handel einen Unterschied zwischen Einkaufs- und Verkaufspreis?',
      'Handelsspanne',
      ['Flügelspannweite', 'Handspanne', 'Zeitspanne'],
      'Die Handelsspanne. Hier wird kein Maßband gebraucht.',
    ],
    [
      'Wortspiel',
      'Wer sich mit einem Geschäftspartner gut versteht, liegt bildlich auf welcher Wellenlänge?',
      'Auf derselben Wellenlänge',
      ['Auf der letzten Frequenz', 'Auf der roten Zahlenlinie', 'Auf dem längsten Kabel'],
      'Auf derselben Wellenlänge. Auch ohne gemeinsames Radiogerät kann die Verständigung stimmen.',
    ],
  ],
  [
    'q07a',
    'v3-07b',
    'v3-07i',
    [
      'BBE',
      'Für welche Handelsbranchen beschreibt BBE ihr Einkaufsplanungstool EKPro ausdrücklich?',
      'Sport- und Fahrradhandel',
      ['Buch- und Musikhandel', 'Apotheken und Optiker', 'Möbel- und Teppichhandel'],
      'Sport- und Fahrradhandel. Die Einkaufsplanung ist auf diese Branchen zugeschnitten.',
      S.ekpro,
    ],
    [
      'BBE',
      'Was plant das von BBE angebotene pepInternet, obwohl sein Name nach einer Online-Pause klingt?',
      'Den Personaleinsatz',
      ['Die Internetwerbung', 'Die Warenanlieferung', 'Die Schaufensterbeleuchtung'],
      'Den Personaleinsatz. Dazu gehören auch Personalbedarf und Zeiterfassung.',
      S.pep,
    ],
    'v3-07d',
    'v3-07e',
    'v3-07f',
    [
      'Wortspiel',
      'Der Absatz steigt: Was nimmt im Vertriebsbericht zu, ohne dass ein Schuh höher wird?',
      'Die verkaufte Menge',
      [
        'Die Höhe des Schuhabsatzes',
        'Die Anzahl der Textabschnitte',
        'Die Schriftgröße der Überschrift',
      ],
      'Die verkaufte Menge. Derselbe Absatz bekommt im Handel eine eigene Bedeutung.',
    ],
    [
      'Wortspiel',
      'Was geschieht beim Kassensturz, wenn das Kassengehäuse dabei heil bleibt?',
      'Der Kassenbestand wird geprüft',
      ['Die Kasse fällt vom Tisch', 'Alle Preise werden gesenkt', 'Das Geschäft zieht um'],
      'Der Kassenbestand wird geprüft. Der Sturz ist hier eine Bestandsaufnahme ohne Fallschaden.',
    ],
  ],
  [
    'v3-08b',
    'v3-08h',
    [
      'BBE',
      'Was soll im BBE Liquiditäts-Cockpit fließen und planbar bleiben?',
      'Ein- und Auszahlungen',
      [
        'Kühlwasser durch die Klimaanlage',
        'Lieferwagen durch eine Schleuse',
        'Getränke durch die Zapfanlage',
      ],
      'Ein- und Auszahlungen. Das Cockpit hilft, den Geldfluss im Blick zu behalten.',
      S.liquid,
    ],
    [
      'BBE',
      'Wohin navigiert der BBE POS-Navigator fachlich, statt eine Straßenroute zu berechnen?',
      'Zur Steuerung von Verkaufskennzahlen',
      [
        'Zur Optimierung von Lieferstrecken',
        'Zur Verwaltung von Urlaubsanträgen',
        'Zur digitalen Bauaktenablage',
      ],
      'Zur Steuerung von Verkaufskennzahlen. Das Ziel liegt am Verkaufsort, nicht am Autobahnkreuz.',
      S.pos,
    ],
    [
      'BBE',
      'Welche drei Perspektiven verbindet BBE laut ihrer Immobilienberatung?',
      'Einzelhandel, Immobilie und Digitalisierung',
      [
        'Produktion, Zoll und Export',
        'Design, Verpackung und Versand',
        'Lohn, Urlaub und Zeiterfassung',
      ],
      'Einzelhandel, Immobilie und Digitalisierung. Ein Gebäude wird dabei aus mehr als einem Blickwinkel betrachtet.',
      S.property,
    ],
    'v3-08c',
    'v3-08e',
    'v3-08f',
    [
      'Wortspiel',
      'Ein Vertrag ist unter Dach und Fach. Was bedeutet das, auch ohne fertiges Bürogebäude?',
      'Er ist erfolgreich abgeschlossen',
      [
        'Er ist in einem Dachbodenfach abgelegt',
        'Er muss noch verhandelt werden',
        'Er gilt nur für Dachdecker',
      ],
      'Er ist erfolgreich abgeschlossen. Der sprichwörtliche Bau ist fertig.',
    ],
    [
      'Wortspiel',
      'Ein Unternehmen schreibt rote Zahlen. Was bedeutet das ohne Angabe der Druckerfarbe?',
      'Es macht Verluste',
      [
        'Es druckt ausschließlich mit Magenta',
        'Es erzielt einen Rekordgewinn',
        'Es hat alle Preise gesenkt',
      ],
      'Es macht Verluste. Schwarzer Toner allein würde daran nichts ändern.',
    ],
  ],
  [
    'v3-09a',
    'v3-09b',
    'v3-09h',
    [
      'BBE',
      'Wie stellt BBE laut ERFA-Angebot vergleichbare Betriebszahlen für den Austausch bereit?',
      'In anonymisierter Form',
      [
        'Als öffentliche Namensrangliste',
        'Nur als frei erfundene Beispielwerte',
        'Ungeprüft nach Unternehmensalphabet',
      ],
      'In anonymisierter Form. Die Zahlen dürfen sich vergleichen lassen, ohne Namensschild.',
      S.erfa,
    ],
    [
      'BBE',
      'Welche Aufgabe übernimmt BBE SKPro im Sport- und Radhandel?',
      'Warensteuerung während der Saison',
      [
        'Tourenplanung für Auslieferungen',
        'Arbeitszeiterfassung der Beschäftigten',
        'Verwaltung von Gebäudeverträgen',
      ],
      'Warensteuerung während der Saison. Dazu gehört, erfolgreiche Artikel rechtzeitig nachzubestellen.',
      S.skpro,
    ],
    'v3-09c',
    'v3-09d',
    'v3-09e',
    'v3-09f',
    [
      'Wortspiel',
      'Jemand wurde beim Geschäft über den Tisch gezogen. Was sagt die Redewendung aus?',
      'Er wurde übervorteilt',
      [
        'Er erhielt den besseren Platz',
        'Er wechselte die Tischseite',
        'Er bekam einen neuen Schreibtisch',
      ],
      'Er wurde übervorteilt. Der Ärger kommt vom Geschäft, nicht von der Tischoberfläche.',
    ],
  ],
  [
    'v3-10a',
    'v3-10b',
    'v3-10h',
    'v3-10j',
    [
      'BBE',
      'Welchen Fachbegriff nennt BBE auf der Immobilienseite als Bezeichnung für ihre Ankaufsprüfung?',
      'Commercial Due Diligence',
      ['Corporate Identity', 'Customer Journey', 'Category Management'],
      'Commercial Due Diligence. Sie liefert vor dem Kauf eine kritische Einschätzung des Investments.',
      S.diligence,
    ],
    'v3-10c',
    'v3-10d',
    'v3-10e',
    'v3-10f',
    'v3-10g',
  ],
];

export function buildBBEQuestions(previous, makeQuestion, freezeTree) {
  const originals = new Map(previous.map((question) => [question.id, question]));
  const firstHundred = BBE_TIERS.flatMap((tier, index) => {
    const level = index + 1;
    if (tier.length !== 10) throw new Error('Quizssoir: each BBE level needs ten questions');
    return tier.map((entry, position) => {
      if (typeof entry === 'string') {
        const original = originals.get(entry);
        if (!original || original.level !== level)
          throw new Error('Quizssoir: invalid immutable BBE question reference ' + entry);
        return original;
      }
      const [category, text, answer, others, explanation, source = null] = entry;
      const id = 'v4-' + String(level).padStart(2, '0') + String.fromCharCode(97 + position);
      return freezeTree({
        ...makeQuestion(id, level, category, text, answer, others, explanation, source),
        visual: null,
        discovery: null,
      });
    });
  });
  // Late reasoning questions remain byte-for-byte unchanged, including diagrams,
  // discoveries, answer order and voice IDs. Old banks never depend on this pool.
  return Object.freeze([...firstHundred, ...previous.filter((question) => question.level >= 11)]);
}
