// Original German writing for the fictional Munich game. These are copy assets,
// not existing voice recordings. Actor IDs describe fictional character roles.
// Event names and suggested cooldowns are data contracts for the integrating system.
export const REACTIVE_LINES = [
  {
    id: 'vault_clean',
    event: 'movement.vault_success',
    actor: 'player',
    text: 'Hürde genommen. Ganz ohne Lenkungsausschuss.',
    cooldown: 25,
    priority: 1,
  },
  {
    id: 'climb_start',
    event: 'movement.climb_start',
    actor: 'player',
    text: 'Der nächste Karriereschritt ist heute überraschend senkrecht.',
    cooldown: 30,
    priority: 1,
  },
  {
    id: 'ledge_reached',
    event: 'movement.ledge_reached',
    actor: 'lena',
    text: 'Gut. Jetzt erst sicher stehen, dann große Sprünge ankündigen.',
    cooldown: 40,
    priority: 1,
  },
  {
    id: 'landing_hard',
    event: 'movement.hard_landing',
    actor: 'player',
    text: 'Uff. Die Landung war nicht Teil der Erfolgsgeschichte.',
    cooldown: 16,
    priority: 2,
  },
  {
    id: 'roof_arrival',
    event: 'movement.roof_arrival',
    actor: 'mara',
    text: 'Hier oben versteht man den Standort. Unten bekommt man wenigstens Kaffee.',
    cooldown: 45,
    priority: 1,
  },
  {
    id: 'roof_wet',
    event: 'movement.wet_roof',
    actor: 'tobias',
    text: 'Die Rutschgefahr ist keine Prognose. Bitte nicht experimentell überprüfen.',
    cooldown: 35,
    priority: 2,
  },
  {
    id: 'suspension_bump',
    event: 'vehicle.hard_bump',
    actor: 'player',
    text: 'Diese Straße hat mehr Unebenheiten als unser Projektplan.',
    cooldown: 35,
    priority: 1,
  },
  {
    id: 'vehicle_scrape',
    event: 'vehicle.scrape',
    actor: 'tobias',
    text: 'Der Lackschaden ist leider keine Rundungsdifferenz.',
    cooldown: 25,
    priority: 2,
  },
  {
    id: 'vehicle_door',
    event: 'vehicle.door_close',
    actor: 'jan',
    text: 'Tür zu. Entscheidung getroffen. So zügig wünsche ich mir unsere Meetings.',
    cooldown: 60,
    priority: 1,
  },
  {
    id: 'vehicle_repaired',
    event: 'vehicle.repaired',
    actor: 'mechanic',
    text: 'Wieder fahrbereit. Die Bordsteine sind weiterhin nicht nachgiebig.',
    cooldown: 30,
    priority: 2,
  },
  {
    id: 'pedestrian_nearmiss',
    event: 'npc.near_miss',
    actor: 'passerby',
    text: 'He! Ich bin zu Fuß unterwegs, nicht im Crashtest!',
    cooldown: 9,
    priority: 3,
  },
  {
    id: 'pedestrian_flee',
    event: 'npc.flee',
    actor: 'passerby',
    text: 'Ich geh hier erst mal aus dem Weg!',
    cooldown: 12,
    priority: 3,
  },
  {
    id: 'witness_call',
    event: 'npc.witness_report',
    actor: 'mara',
    text: 'Das eskaliert gerade. Und diesmal hilft keine neue Folie.',
    cooldown: 30,
    priority: 3,
  },
  {
    id: 'police_spotted',
    event: 'police.spotted',
    actor: 'officer',
    text: 'Sie dort! Bitte bleiben Sie stehen.',
    cooldown: 9,
    priority: 4,
  },
  {
    id: 'police_stop',
    event: 'police.vehicle_stop',
    actor: 'officer',
    text: 'Fahren Sie rechts ran und stellen Sie den Motor ab.',
    cooldown: 12,
    priority: 4,
  },
  {
    id: 'police_search',
    event: 'police.search',
    actor: 'officer',
    text: 'Sichtkontakt verloren. Wir prüfen die nächste Querstraße.',
    cooldown: 20,
    priority: 2,
  },
  {
    id: 'wanted_cleared',
    event: 'police.clear',
    actor: 'player',
    text: 'Wieder ruhig. Vielleicht jetzt eine Karriere mit weniger Blaulicht.',
    cooldown: 60,
    priority: 2,
  },
  {
    id: 'crate_shifted',
    event: 'prop.crate_moved',
    actor: 'player',
    text: 'Endlich mal ein Arbeitspaket, das man wirklich verschieben kann.',
    cooldown: 35,
    priority: 1,
  },
  {
    id: 'bin_toppled',
    event: 'prop.bin_toppled',
    actor: 'lena',
    text: 'Die Tonne war vorher ordentlich sortiert. Das gilt übrigens auch für Daten.',
    cooldown: 35,
    priority: 1,
  },
  {
    id: 'prop_chain',
    event: 'prop.chain_reaction',
    actor: 'tobias',
    text: 'Eine Änderung, sechs Folgeprobleme. Die Simulation ist erschreckend realistisch.',
    cooldown: 40,
    priority: 2,
  },
  {
    id: 'garage_enter',
    event: 'location.garage_enter',
    actor: 'jan',
    text: 'Hier unten steht unser Fuhrpark. Das Wachstum parkt offenbar woanders.',
    cooldown: 60,
    priority: 1,
  },
  {
    id: 'rain_start',
    event: 'weather.rain_start',
    actor: 'mara',
    text: 'Regen. Dann bekommt der Außentermin eben eine Überdachung.',
    cooldown: 90,
    priority: 1,
  },
  {
    id: 'thunder_near',
    event: 'weather.thunder_near',
    actor: 'tobias',
    text: 'Das war keine Mail-Benachrichtigung. Ich würde kurz unter ein Dach gehen.',
    cooldown: 75,
    priority: 2,
  },
  {
    id: 'fog_arrives',
    event: 'weather.fog_start',
    actor: 'lena',
    text: 'Schlechte Sicht. Wir reduzieren das Tempo, nicht die Sorgfalt.',
    cooldown: 90,
    priority: 2,
  },
  {
    id: 'sun_returns',
    event: 'weather.sun_return',
    actor: 'player',
    text: 'Sonne. Die erste positive Entwicklung heute ohne Fußnote.',
    cooldown: 90,
    priority: 1,
  },
];

// TASKS-compatible core fields. Route and dialogue metadata stay separate so
// adding this task does not bypass Simulation.accept()/finish() or daily saves.
export const BRIEFCASE_TASK = {
  type: 'briefcase',
  title: 'Der Koffer mit der wirklich finalen Fassung',
  brief:
    'Ein Kurier hat den BBE-Musterkoffer versehentlich im Hinterhof abgestellt. Hole ihn zurück und bringe ihn zum Empfang. Hofzufahrt, Dachweg oder Tiefgarage: Wähle deinen Weg. Der Koffer muss ankommen; einen Stuntbonus haben wir nicht vereinbart.',
  base: 55,
  min: 1,
  rep: 0,
  minutes: 180,
  location: 'BBE-Hinterhof → BBE-Empfang',
};

export const BRIEFCASE_MISSION = {
  id: 'briefcase',
  giver: 'lena',
  itemName: 'BBE-Musterkoffer',
  destination: { zone: 'office', interaction: 'reception', label: 'BBE-Empfang' },
  pickup: { zone: 'city', x: 76, z: 54, label: 'Hinterhof seitlich des BBE-Büros' },
  progressKeys: ['briefed', 'route:street', 'route:roof', 'route:garage', 'picked', 'delivered'],
  completionRequires: ['picked', 'delivered'],
  routes: [
    {
      id: 'street',
      title: 'Durch die Hofzufahrt',
      description:
        'Auf Straßenniveau durch die Gasse am BBE-Hof. Der direkte Weg mit den wenigsten Höhenmetern.',
      entry: { zone: 'city', x: 62.5, z: 44 },
      dialogueId: 'case_route_street',
    },
    {
      id: 'roof',
      title: 'Über den Dachweg',
      description:
        'Über die Leiter am BBE-Seitenflügel und den Dachweg. Gute Übersicht, aber bei Regen vorsichtig bewegen.',
      entry: { zone: 'city', x: 60, z: 53 },
      dialogueId: 'case_route_roof',
    },
    {
      id: 'garage',
      title: 'Durch die Tiefgarage',
      description:
        'Den überdachten Durchgang zum Hinterhof nutzen. Wegweiser beachten; der Koffer steht nicht in einem Auto.',
      entry: { zone: 'city', x: 76, z: 47 },
      dialogueId: 'case_route_garage',
    },
  ],
  dialogue: [
    {
      id: 'case_briefing',
      actor: 'lena',
      event: 'mission.briefing',
      text: 'Unser Musterkoffer steht im Hinterhof. Im Koffer sind Unterlagen, auf den Unterlagen steht final. Der Kurier hat daraus geschlossen, dass das Projekt schon vorbei ist. Bring ihn bitte zum Empfang zurück.',
    },
    {
      id: 'case_routes',
      actor: 'mara',
      event: 'mission.routes',
      text: 'Du kommst über die Hofzufahrt, den Dachweg oder die Tiefgarage hin. Ich würde nach Wetter und Laune entscheiden. Das ist übrigens mehr Methodik, als manche Standortentscheidung bekommt.',
    },
    {
      id: 'case_route_street',
      actor: 'lena',
      event: 'mission.route_street',
      text: 'Die Hofzufahrt ist völlig in Ordnung. Ein kurzer Weg wird nicht schlechter, nur weil er sich auf keiner Luftaufnahme erklären lässt.',
    },
    {
      id: 'case_route_roof',
      actor: 'mara',
      event: 'mission.route_roof',
      text: 'Über die Dächer? Dann nimm die Leiter am Seitenflügel. Oben erst stehen bleiben und den nächsten Absatz ansehen. Mut ersetzt keine Landefläche.',
    },
    {
      id: 'case_route_garage',
      actor: 'tobias',
      event: 'mission.route_garage',
      text: 'Die Tiefgarage ist trocken und führt zum Hof. Folge den Ausgangsschildern. Die Parkplatznummern sind ausnahmsweise keine Kennzahlen.',
    },
    {
      id: 'case_pickup',
      actor: 'player',
      event: 'mission.pickup',
      text: 'Gefunden. Der Koffer ist schwerer als die Management Summary vermuten lässt.',
    },
    {
      id: 'case_carry',
      actor: 'lena',
      event: 'mission.carry',
      text: 'Gut. Jetzt zum BBE-Empfang. Für den Rückweg reicht eine normale Fortbewegungsart vollkommen aus.',
    },
    {
      id: 'case_dropped',
      actor: 'mara',
      event: 'mission.dropped',
      text: 'Der Koffer liegt noch da. Sammle ihn wieder ein. Verloren ist erst mal nur der elegante Teil deiner Route.',
    },
    {
      id: 'case_recovery',
      actor: 'lena',
      event: 'mission.recovery',
      text: 'Der Koffer wurde wieder im Hof bereitgestellt. Dein Auftrag bleibt offen. Du kannst diesmal einen anderen Weg nehmen; im Abschlussbericht steht nur, ob er angekommen ist.',
    },
    {
      id: 'case_resume',
      actor: 'tobias',
      event: 'mission.resume',
      text: 'Der Fortschritt ist gespeichert. Prüfe kurz dein Auftragsziel. Wir müssen den Koffer nicht noch einmal abholen, wenn du ihn bereits dabeihast.',
    },
    {
      id: 'case_success',
      actor: 'lena',
      event: 'mission.success',
      text: 'Koffer da, Unterlagen vollständig, Termin gerettet. Genau so sieht eine saubere Übergabe aus. Die drei Pixel am Logo besprechen wir nach dem Mittagessen.',
    },
    {
      id: 'case_success_roof',
      actor: 'jan',
      event: 'mission.success_roof',
      text: 'Die Lieferung ist angekommen. Den ungewöhnlichen Weg lasse ich als Standorterkundung durchgehen. Bei Reisekosten schreiben wir trotzdem nicht Luftlinie hinein.',
    },
    {
      id: 'case_success_street',
      actor: 'jan',
      event: 'mission.success_street',
      text: 'Ein Auftrag, ein direkter Weg, eine fertige Übergabe. Effizienz ist manchmal erstaunlich unspektakulär. Behalte das bitte bei.',
    },
    {
      id: 'case_success_garage',
      actor: 'mara',
      event: 'mission.success_garage',
      text: 'Trocken geblieben und pünktlich geliefert. Die Tiefgarage war heute offenbar unser bester Standortfaktor.',
    },
    {
      id: 'case_late',
      actor: 'lena',
      event: 'mission.deadline',
      text: 'Der Termin ist inzwischen vorbei. Das ärgert mich, aber beim nächsten Auftrag setzen wir früher einen Wegpunkt. Der Koffer braucht jetzt vor allem einen festen Abstellplatz.',
    },
  ],
  hud: {
    accepted: 'Hole den BBE-Musterkoffer aus dem Hinterhof.',
    carrying: 'Koffer dabei · Zurück zum BBE-Empfang.',
    dropped: 'Koffer abgestellt · Wieder aufheben oder Auftrag zurücksetzen.',
    recovered: 'Koffer zurück im Hinterhof · Du kannst einen neuen Weg wählen.',
    delivered: 'Übergabe vollständig · Vergütung wurde abgerechnet.',
  },
};
