export const WORKSHOP_LINES = [
  {
    id: 'story_intro_01',
    actor: 'lukas',
    event: 'workshop.story',
    text: 'Heute braucht der Kunde keine Folie.',
    duration: 3.418,
    key: 'intro_01',
    speaker: 'Lukas Fleischmann',
  },
  {
    id: 'story_intro_02',
    actor: 'player',
    event: 'workshop.story',
    text: 'Sondern?',
    duration: 1.3366,
    key: 'intro_02',
    speaker: 'Du',
  },
  {
    id: 'story_intro_03',
    actor: 'lukas',
    event: 'workshop.story',
    text: 'Diesen Workshop-Koffer. Clara wartet am Marienplatz.',
    duration: 5.426,
    key: 'intro_03',
    speaker: 'Lukas Fleischmann',
  },
  {
    id: 'story_intro_04',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Adapter, Karten, Stifte. Diesmal sogar funktionierende.',
    duration: 6.4344,
    key: 'intro_04',
    speaker: 'Tobias',
  },
  {
    id: 'story_intro_05',
    actor: 'lukas',
    event: 'workshop.story',
    text: 'Tobias navigiert. Du fährst.',
    duration: 4.1361,
    key: 'intro_05',
    speaker: 'Lukas Fleischmann',
  },
  {
    id: 'story_intro_06',
    actor: 'player',
    event: 'workshop.story',
    text: 'Verstanden. Ein Projekt mit Sitzplatzgarantie.',
    duration: 4.1389,
    key: 'intro_06',
    speaker: 'Du',
  },
  {
    id: 'story_meet_01',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Koffer da. Auto da. Für einen Montag ist das verdächtig rund.',
    duration: 6.1908,
    key: 'meet_01',
    speaker: 'Tobias',
  },
  {
    id: 'story_meet_02',
    actor: 'player',
    event: 'workshop.story',
    text: 'Du nimmst den Beifahrersitz. Den Termin leitet heute das Navi.',
    duration: 4.874,
    key: 'meet_02',
    speaker: 'Du',
  },
  {
    id: 'story_meet_03',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Abgemacht. Ich kümmere mich um Strecke, Adapter und konstruktive Zwischenrufe.',
    duration: 6.8508,
    key: 'meet_03',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_01',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Angeschnallt. Erst über den Königsplatz. Wir haben sogar mal einen klaren Weg.',
    duration: 7.3021,
    key: 'drive_01',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_02',
    actor: 'player',
    event: 'workshop.story',
    text: 'Am Königsplatz bitte keine Benchmark-Runde. Clara wartet.',
    duration: 4.6177,
    key: 'drive_02',
    speaker: 'Du',
  },
  {
    id: 'story_drive_03',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Schade. Die Säulen hier sind ausgesprochen managementtauglich.',
    duration: 5.2994,
    key: 'drive_03',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_04',
    actor: 'player',
    event: 'workshop.story',
    text: 'Nächster Halt: Karolinenplatz. Danach geht es weiter Richtung Altstadt.',
    duration: 5.8453,
    key: 'drive_04',
    speaker: 'Du',
  },
  {
    id: 'story_drive_05',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Kurze Frage: Auf dem Stick liegt final, final neu oder wirklich final?',
    duration: 6.266,
    key: 'drive_05',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_06',
    actor: 'player',
    event: 'workshop.story',
    text: 'Die Version, die du gestern um dreiundzwanzig Uhr geschickt hast.',
    duration: 4.636,
    key: 'drive_06',
    speaker: 'Du',
  },
  {
    id: 'story_drive_07',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Dann ist sie historisch. Heute Morgen wollte jemand das Logo drei Pixel nach links.',
    duration: 6.8509,
    key: 'drive_07',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_08',
    actor: 'player',
    event: 'workshop.story',
    text: 'Gut, dass wir fahren. Stillstand wäre in diesem Projekt ja verdächtig.',
    duration: 5.8018,
    key: 'drive_08',
    speaker: 'Du',
  },
  {
    id: 'story_drive_09',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Der Adapter steckt im Koffer. Ohne den wären wir nur zwei Menschen mit einer Vision.',
    duration: 6.4535,
    key: 'drive_09',
    speaker: 'Tobias',
  },
  {
    id: 'story_drive_10',
    actor: 'player',
    event: 'workshop.story',
    text: 'Und Moderationskarten. Damit hätten wir wenigstens eine analoge Ausweichstrategie.',
    duration: 6.1327,
    key: 'drive_10',
    speaker: 'Du',
  },
  {
    id: 'story_drive_11',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Da ist der Marienplatz. Clara wartet schon. Ab hier kommt der Koffer mit.',
    duration: 6.6939,
    key: 'drive_11',
    speaker: 'Tobias',
  },
  {
    id: 'story_handoff_01',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Da seid ihr ja. Willkommen am Marienplatz. Ist das unser Workshop-Koffer?',
    duration: 6.482,
    key: 'handoff_01',
    speaker: 'Clara',
  },
  {
    id: 'story_handoff_02',
    actor: 'player',
    event: 'workshop.story',
    text: 'Persönlich geliefert. Und mit mehr Qualitätskontrolle, als der Dateiname vermuten lässt.',
    duration: 6.735,
    key: 'handoff_02',
    speaker: 'Du',
  },
  {
    id: 'story_handoff_03',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Ich schaue kurz rein. Adapter, Moderationskarten, Stifte. Alles da.',
    duration: 7.1204,
    key: 'handoff_03',
    speaker: 'Clara',
  },
  {
    id: 'story_handoff_04',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Sogar Stifte, die schreiben. Wir liefern heute ungewöhnlich belastbare Ergebnisse.',
    duration: 7.3113,
    key: 'handoff_04',
    speaker: 'Tobias',
  },
  {
    id: 'story_handoff_05',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Sehr gut. Dann sehen wir uns heute Abend im Workshopraum bei der Frauenkirche.',
    duration: 5.8904,
    key: 'handoff_05',
    speaker: 'Clara',
  },
  {
    id: 'story_workshop_01',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Schön, dass ihr wieder da seid. Der Raum ist bereit, und der Kaffee auch.',
    duration: 6.2905,
    key: 'workshop_01',
    speaker: 'Clara',
  },
  {
    id: 'story_workshop_02',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Ich stecke den Adapter ein. Das ist der Moment, in dem aus Beratung endlich Verbindung wird.',
    duration: 7.37,
    key: 'workshop_02',
    speaker: 'Tobias',
  },
  {
    id: 'story_workshop_03',
    actor: 'player',
    event: 'workshop.story',
    text: 'Bild ist da. Karten liegen bereit. Wir können mit euren wichtigsten Fragen anfangen.',
    duration: 6.7,
    key: 'workshop_03',
    speaker: 'Du',
  },
  {
    id: 'story_workshop_04',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Wie schaffen wir ein Sortiment, das unsere Kunden wirklich brauchen?',
    duration: 4.931,
    key: 'workshop_04',
    speaker: 'Clara',
  },
  {
    id: 'story_workshop_05',
    actor: 'player',
    event: 'workshop.story',
    text: 'Wir sammeln zuerst ihre Bedürfnisse. Dann prüfen wir Zahlen, Lücken und konkrete Maßnahmen.',
    duration: 7.0723,
    key: 'workshop_05',
    speaker: 'Du',
  },
  {
    id: 'story_workshop_06',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Und jede Maßnahme bekommt einen Verantwortlichen. Das Flipchart hat sich leider nicht freiwillig gemeldet.',
    duration: 7.8042,
    key: 'workshop_06',
    speaker: 'Tobias',
  },
  {
    id: 'story_workshop_07',
    actor: 'clara',
    event: 'workshop.story',
    text: 'Das war hilfreich. Klarer Plan, ehrliche Antworten. Genau dafür haben wir euch eingeladen.',
    duration: 7.946,
    key: 'workshop_07',
    speaker: 'Clara',
  },
  {
    id: 'story_success_01',
    actor: 'Tobias',
    event: 'workshop.story',
    text: 'Eine letzte Änderung: Feierabend.',
    duration: 3.4396,
    key: 'success_01',
    speaker: 'Tobias',
  },
];
